### PR TITLE
Update to Angular 10

### PR DESCRIPTION
**Pull request by nntndfrk**

### CODE REVIEW

**Comment by luke-rogers** [comment]
Can we get this merged and released?

**Comment by Esargent01** [comment]
Not having this is causing a warning in my current version of Angular (12). Can we get this released please?

**Comment by EOussama** [comment]
This package seriously needs more maintainers, that or a better fork should be in the works.

**Comment by 8odoris** [comment]
Please get this released as soon as possible. Dependencies are too strict.

**Pull request merged**
