### PR TITLE
updated package

### PR DESCRIPTION
**Pull request by pegaltier**
https://github.com/AlisonVilela/ngx-zendesk-webwidget/issues/11

### CODE REVIEW

**Comment by mackelito** [comment]
When will this be merged and updated?

**Comment by pegaltier** [comment]
@AlisonVilela want to work this week-end on this! maybe on monday!

**Comment by mackelito** [comment]
Any updates @pegaltier @AlisonVilela  ?

**Comment by mackelito** [comment]
@pegaltier I see that you have a fork with this update.. would you consider making it a new npm package? (pleeeeeease 🙏 )

**Pull request closed without merging**
