### PR TITLE
feat(service): setSettings(settings) -> window.zESettings = settings

### PR DESCRIPTION
**Pull request by davious**

### CODE REVIEW

**Comment by andrevmc** [comment]
The setSettings (settings) method is not setting window.zESettings. Is this a bug?

**Comment by mackelito** [comment]
@andrevmc if you like you can try my fork at https://github.com/mackelito/ng-zendesk-webwidget

**Comment by andrevmc** [comment]
It's OK,

Thanks and I saw your gitHub.


*André Vinicius Moraes da Costa*
avmcosta@gmail.com
(21) 98355-7332



Em ter, 16 de abr de 2019 às 04:48, Markus Thiel <notifications@github.com>
escreveu:

**Comment by andrevmc** [comment]
In my project I'm not only getting the the departments. I do not have what is happening

**Pull request merged**
